name: trippin
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^1.0.3   
  animated_splash_screen: ^1.2.0  
  curved_navigation_bar: ^1.0.6
  percent_indicator: ^3.4.0
  intl: ^0.18.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/fonts/
    - lib/images/splash/
    - lib/images/dashboard/
    - lib/images/dashboard/list-menu/
    - lib/images/dashboard/
    - lib/images/home/
    - lib/images/login/
    - lib/images/dashboard/album/
    - lib/images/recommend/
    - lib/images/success/
    - lib/images/activity_detail/
    - lib/images/add_activity/
  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Black.ttf
        - asset: assets/fonts/Inter-Bold.ttf
          weight: 700
        - asset: assets/fonts/Inter-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Inter-Light.ttf
          weight: 300
        - asset: assets/fonts/Inter-Medium.ttf
          weight: 500
        - asset: assets/fonts/Inter-Regular.ttf
        - asset: assets/fonts/Inter-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Inter-Thin.ttf
          weight: 100
  
    # kalo ada tambah pages masukin assetsnya disini