name: trippin
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^1.0.3   
  animated_splash_screen: ^1.2.0  
  curved_navigation_bar: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - lib/images/splash/bg.png
    - lib/images/splash/logo.png
    - lib/images/dashboard/back.png
    - lib/images/dashboard/info.png
    - lib/images/dashboard/list-menu/
    - lib/images/dashboard/shop.svg
    - lib/images/dashboard/play.svg
    - lib/images/dashboard/food.svg
    - lib/images/home/
    - lib/images/login/
    - lib/images/dashboard/album/
    # kalo ada tambah pages masukin assetsnya disini